### ISSUE TITLE
Clarification on a couple of the topic prompts

### ISSUE THREAD

**Issue by glenjamin** [ConfluxDigital/software-delivery-assessment#2]
I recently ran a session using the Team Health prompts, and a few questions had us discussing what we thought the intent of the question was, or some of the wording choices.

> 1. Easy to release - how easy is it to release a change to the software you work on?
> It is difficult to release a change
> It is easy and exciting to release a change

We think that "exciting" releases are a bad thing. Releases should ideally be normal and bording.

> 2. Suitable process - how suitable is the process for developing software?
> The process is cumbersome and unhelpful
> The process is mostly hidden and we barely feel it

We were unclear what was meant by the _"process for developing"_ - is this about the delivery process, or about the act of typing into our editors? We went with the former.

Is this about the day-to-day process, or the longer term planning process? We went with the former.

We suggest perhaps changing "developing" to "delivering"?

**Comment by matthewskelton** [comment]
Thanks, @glenjamin - good points. 

I agree that releases should not be A Big Thing. For some orgs "exciting" is a good thing but not all orgs :) . How about "It is easy and straightforward to release a change" ?

Some of the wording is deliberately open to interpretation so that it's useful for different situations. It should be up to the team to decide what angle is most useful for them. My intent with the "process for developing" question was to identify things that get in the way of software development & delivery. How about "how suitable is the process for developing and delivering software?"

I'd be happy with a PR for these two changes - I think they clarify the intent. Thank you for trying out the assessment and the feedback!
